version:     '3.8'

services:

  db:
    image:   postgres
    restart: always
    environment:
      POSTGRES_DB: 'nest_blog'
      POSTGRES_USER:     'root'
      POSTGRES_PASSWORD: 'root'
    ports:
      - 5001:5432
  adminer:
    image:   adminer
    restart: always
    ports:
      - 8080:8080
